language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t arunhotra/reactt-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true arunhotra/react-test npm test -- --coverage

after_success:
  - docker build -t arunhotra/multi-client ./client
  - docker build -t arunhotra/multi-nginx ./nginx
  - docker build -t arunhotra/multi-server ./server
  - docker build -t arunhotra/multi-worker ./worker
  #login to dockercli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push the images built to dockerhub
  - docker push arunhotra/multi-client
  - docker push arunhotra/multi-nginx
  - docker push arunhotra/multi-server
  - docker push arunhotra/multi-worker
# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-2"
#   app: "docker-react"
#   env: "DockerReact-env"
#   bucket_name: "elasticbeanstalk-us-west-2-121637458170"
#   bucket_path: "docker-react"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
